version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:14-browsers  # or any other language docker image you need

jobs:
  build:
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            npm install  

      - run:
          name: Run SonarQube Scan
          command: |
            sonar-scanner -Dsonar.projectKey=APDS7311POE-ST10144453_APDS7311-POE \
              -Dsonar.organization=apds7311poe-st10144453 \
              -Dsonar.sources=. \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$7a6696e70161ced02ef7156a71863b9ed8a47ed6

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
