name: Deploy Backend

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --verbose
        working-directory: ./server

      # Remove this step if no build script is necessary
      # - name: Build project
      #   run: npm run build
      #   working-directory: ./server

      - name: Create .env file
        run: |
          echo "CONNECTION_STRING=${{ secrets.CONNECTION_STRING }}" >> .env
          echo "ENCRYPTION_KEY=${{ secrets.ENCRYPTION_KEY }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "MY_SECRET_PEPPER=${{ secrets.MY_SECRET_PEPPER }}" >> .env
        working-directory: ./server

      - name: Deploy to Server
        run: |
          # Deployment script here
        working-directory: ./server
        env:
          CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          MY_SECRET_PEPPER: ${{ secrets.MY_SECRET_PEPPER }}
