name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16, 18]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: ./server

      - name: Run tests
        run: npx mocha tests/generatecrypto.test.mjs
        working-directory: ./server

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: server/test-results/results.xml

      - name: Publish test results to Dorny
        uses: dorny/test-reporter@v1
        with:
          name: Mocha Tests
          path: server/test-results/results.xml
          reporter: mocha-junit-reporter
