name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x, 18.x, 20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: ./server

      - name: Create test results directory
        run: mkdir -p server/test-results
        working-directory: ./server

      - name: Run tests
        run: npx mocha tests/generatecrypto.test.mjs --reporter mocha-junit-reporter --reporter-options mochaFile=server/test-results/results.xml
        working-directory: ./server

      - name: List test results directory
        run: ls -la server/test-results
        working-directory: ./server

      - name: Add delay
        run: sleep 5

      - name: Debug:List GitHub workspace
        run: ls -la ${{ github.workspace }}
        working-directory: ./server

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ${{ github.workspace }}/server/test-results/results.xml
          if-no-files-found: warn
          include-hidden-files: false

      - name: Publish test results to Dorny
        uses: dorny/test-reporter@v1
        with:
          name: Mocha Tests
          path: ${{ github.workspace }}/server/test-results/results.xml
          reporter: mocha-json
